### ISSUE TITLE
Observação da Área de Edição de Automações

### ISSUE THREAD

**Issue by AdrianoTRibeiro** [clioapp/acelle-mail#1]
![dica](https://user-images.githubusercontent.com/33559833/74426541-4f10fa00-4e34-11ea-888f-434d238cd267.png)

Seria interessante ou aumentar o tamanho do retângulo ali ou criar um recurso pra caso o cliente deixe o ponteiro do mouse em cima do retângulo e a mensagem possa ser exibida completamente caso ela ultrapasse o campo

**Comment by cfachinelli** [comment]
Todas melhorias devem ser tratadas com o Leonardo
