### ISSUE TITLE
Dúvida na área de edição da tradução em Português

### ISSUE THREAD

**Issue by AdrianoTRibeiro** [clioapp/acelle-mail#2]
![Era pra ser assim](https://user-images.githubusercontent.com/33559833/74426777-b4fd8180-4e34-11ea-9250-14dcbb673d25.png)

Era pra ser assim nessas partes??

**Comment by cfachinelli** [comment]
Comportamento já explicado via Hangout, é como palavras com espaço devem ser tratadas quando usadas como chave da tradução
