### ISSUE TITLE
Carregamento eterno 

### ISSUE THREAD

**Issue by AdrianoTRibeiro** [clioapp/acelle-mail#3]
![Hoje_12_02_2020_14_10](https://user-images.githubusercontent.com/33559833/74426986-1c1b3600-4e35-11ea-93b4-9a1d46f6ae3d.png)

A lista de automações criada simplesmente não é carregada. Iniciou ontem depois da volta do server e continua até agora

**Comment by AdrianoTRibeiro** [comment]
![image](https://user-images.githubusercontent.com/33559833/74454015-07a16280-4e62-11ea-912b-e3549ad2459b.png)

![image](https://user-images.githubusercontent.com/33559833/74454118-2acc1200-4e62-11ea-96ac-f800ef9c2e28.png)


Na área de Admin da página > na área de clientes e "subscritores" tá carregando a lista

**Comment by cfachinelli** [comment]
corrigido pelo Acelle
