### ISSUE TITLE
Sobre as Traduções

### ISSUE THREAD

**Issue by AdrianoTRibeiro** [clioapp/acelle-mail#4]
[anotacoes_marcacoes_Traducao_Automacao_de_marketing.txt](https://github.com/clioapp/acelle-mail/files/4197875/anotacoes_marcacoes_Traducao_Automacao_de_marketing.txt)
[traduções não encontradas.txt](https://github.com/clioapp/acelle-mail/files/4197876/traducoes.nao.encontradas.txt)

Primeiro => Lista de traduções encontradas

Segundo => Lista de traduções não encontradas

**Comment by cfachinelli** [comment]
- Painel de Controle 
- [ ] Painel de Controle > Utilização > Subscritor mudar para Leads ou Assinantes
- [ ] Painel de Controle > Crescimento de Lista > Quando selecionar a opção diferente de Todos > Nome da Lista (0 subscribers) para 0 assinantes ou leads
- Automações
- [ ] Automações > Lista de automações criadas > abaixo do número de contatos > Contacts para Contatos =>
- [ ] Automações > Lista de automações criadas > palavra Paused para Pausado
- [ ] Quando for editar  automação criada mensagem: Automation starts when the following trigger condition is met para A Automação inicia quando a seguinte condição for satisfeita/A Automação começará quando as seguintes condições forem satisfeitas
- [ ] Na barra de opções > Last Saved para Salvo pela última vez: > <- Go back para voltar >Switch automation para alternar automação/Trocar automação
- Na edição da da automação:

- [ ] Interruptor escrito Paused par Pausado /// Quando clicado palavra Running para Executando(??)
- [ ] botão de settings para Configurações
- [ ] Na aba abaixo a palavra Setting para Configuração 
- [ ] Nas Opções de Setting(Configuração) > botão Save
- [ ] Nas opções de settings(configuração) > botão Delete
- [ ] na aba Insight > Contacts/Involved/%Complete
- [ ] Na aba Insight > Trigger
- [ ] Na aba Statistics > nas opções Timeline para linha do tempo/ All contacts para Todos os contatos/ Trigger para Ação(???)
- [ ] Na aba Statistics > Todos os Contatos > Barra de pesquisa > Enter to Search contatcs...
- [ ] Na árvore de Criação da árvre de condições > + > Janela > Wait e Condition
- [ ] Na árvore de Criação da árvre de condições > + > Janela > Send Email > Aba Setup para configuração
- [ ] NA árvore de Criação da árvre de condições > + > Janela > Send Email > Aba Setup > Setup EMail para Configuração de Email
- [ ] Na árvore de Criação da árvre de condições > + > janela > Sendo Email > Aba Setup > Abaixo de Setup Email > Please fill-up email information below. They will be used to apply to all emails that send to customers. para Preencha as informações de email abaixo. Eles serão usados para aplicar a todos os emails enviados aos clientes.
- [ ] Na Criação da árvre de condições > + > Janela > Send Email > Aba Setup > Abaixo de Responder a* > E.g noreply@domain.com para Por Exemplo...
- [ ] Na criação da árvore de condições > + > Janela > Confirm para Confirmar(?????)
- [ ] Na criação da árvore de condições > + > Janela > aba Confirm > Palavra Subject/ from / Content / Tracking (Opens/Clicks)
- [ ] Na criação da árvore de condições > + > Janela > aba confirm > botões Setup e Update
- [ ] Na Criação da árvore de condições > bloco criado para mandar email > Send Email ':name' 
- [ ] Na Criação da árvre de condições > clicando no ação não configurado > Janela de Automação de trigger > Boas Vindas > Janela > botão confirm
- [ ] Na criação da árvore de condições > clicando na ação não configurada > Janela de Automação de Trigger > Deseje "Feliz Aniversário" > Coisas como Before, At e botão de confirm
- [ ] na criação da árvore de condições > clicando na ação não configurada > Janela > Data específica > o nome dos meses
- [ ] na criação da árvore de condições > clicando na ação não congigurada > Janela > API 3.0 > 
- [ ] Automation is triggered manually or from another application using Acelle Mail API 3.0. Make an HTTP POST request to the API endpoint below
- [ ] na criação da árvore de condições > clicando para gerar uma condição > a direita da página > botão Delete this Action
- [ ] na criação da árvore de condições > clicando para gerar uma condição > a direita da página > Change Trigger
- [ ] na criação da árvore de condições > as frases new contact subscribe to mail list e send to :nome
- [ ] Na criação da árvore de condições > criando uma condição >Janela
- [ ] Janela > Abaixo de Selecionar critério > Subscriber read an Email para Assinante leu um email
- [ ] Janela > Abaixo de Selecionar critério > Subscrever clicks on a Link para Assinante clica em um Link
- [ ] Janela > Which email subscriber reads para Quando o assinante de email lê
- [ ] árvore de criação de condição > texto da condição criada > Condition: Open previuos email? para Condição: Abrir email anterior? => linha 2672 *** traduziu em algum lugar
- [ ] árvore de criação de condições > Y par S
- [ ] Na criação da árvore de condições > Wait 
- [ ] Janela > wait
- [ ] Menus > Enviar > Enviar Identidade > Aba Domains e a palavra dentro desta aba, palavra Domains
- [ ] Menus > Enviar > Lista negra > Import

**Comment by AdrianoTRibeiro** [comment]
![image](https://user-images.githubusercontent.com/33559833/74684070-9fc48200-51a9-11ea-963a-bf3712989a66.png)
